name: CI
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      - name: Lint
        run: flake8 .
      - name: Format (check)
        run: black --check .

  deps:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Try installing project deps (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requerimientos.txt ]; then pip install -r requerimientos.txt; fi
