name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint (required) + Format check (advisory)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requerimientos.txt') }}-py310
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      # Fail only on fatal issues
      - name: flake8 (required - fatal rules only)
        run: flake8 . --select=E9,F63,F7,F82

      # Advisory only
      - name: black (format check - advisory)
        run: |
          black --check . || (echo "::warning ::Black found formatting issues (advisory only)"; exit 0)

  deps:
    name: Install project deps (optional, never fails)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requerimientos.txt') }}-py310
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Try installing dependencies (non-fatal)
        shell: bash
        run: |
          set +e
          python -m pip install --upgrade pip
          if [ -f requerimientos.txt ]; then pip install -r requerimientos.txt; fi
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning ::Dependency installation failed with exit code $status (ignored)"
            exit 0
          fi
          echo "Dependencies installed successfully."
